name: deploy-mainfests

on:
  push:
    branches: [ main ]
    paths:
      - infra/**
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        env:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az aks get-credentials --resource-group TixGit --name ticketing
      - run: kubectl config use-context ticketing
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
